llm:
  url: http://localhost:8000
server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frauddb
    username: root
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver
